<?php

namespace App;

use App\Base\Client as BaseClient;
use TheCodingMachine\GraphQLite\Annotations\Field;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * Skeleton subclass for representing a row from the 'client' table.
 *
 * Tablas para nuestros Clientes
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
#[Type]
class Client extends BaseClient
{

    #[Field]
    public function getId(): string
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getName(): string
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getLastName(): string
    {
        return parent::getLastName(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getAddress(): string
    {
        return parent::getAddress(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getZipCode(): int
    {
        return parent::getZipCode(); // TODO: Change the autogenerated stub
    }
}
