<?php

namespace App;

use App\Base\Product as BaseProduct;
use Propel\Runtime\Connection\ConnectionInterface;
use TheCodingMachine\GraphQLite\Annotations\Field;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * Skeleton subclass for representing a row from the 'product' table.
 *
 * Tabla de Productos
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
#[Type]
class Product extends BaseProduct
{

    #[Field]
    public function getId(): string
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getName(): string
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getPrice(): float
    {
        return parent::getPrice(); // TODO: Change the autogenerated stub
    }

    #[Field]
    public function getCategory(): Category
    {
        return parent::getCategoryRelatedByCategoryId(); // TODO: Change the autogenerated stub
    }
}
